### ISSUE TITLE
Empty divs remaining on page blocking mouse functions.

### ISSUE THREAD

**Issue by vswood** [fabien-d/alertify.js#146] opened 2013-07-01 14:22 UTC
I'm using alertify on a google map app. There are icons at the top of the page from google maps drawing manager. After the alertify alert is shown and dismissed, a small amount of inviv\sible dialog remains hanging down at the top of the page, preventing interaction with the icons beneath it. This element should be either hidden or removed, rather than remaining and interfering with other elements on the page.

**Comment by fabien-d** [comment] 2013-07-02 00:06
Looks like a duplicate of #138. See if the workaround in that issue works for you. Still haven't had a chance to implement a fix.

**Comment by vswood** [comment] 2013-07-02 12:26
Didn't see that ticket. Works like a charm. Thanks.

**Comment by fabien-d** [comment] 2013-07-06 14:49
Fixed with ^ PR

**Closed as completed by fabien-d** 2013-07-06 14:49 UTC
