### ISSUE TITLE
alertify.prompt scrolls the page to the top (default theme, chrome 18)

### ISSUE THREAD

**Issue by dschwen** [fabien-d/alertify.js#83] opened 2013-01-09 23:36 UTC
When I trigger a prompt dialog at the bottom of a long page the document jumps to the very top. I'm using the default theme and (the rather old Chrome 18, cannot update on this machine will try with a newer chrome)

Also when the dialog opens and the page scrolls, the entire page flashes black for a split second.

I don't see why this is happening, given that position fixed is used on the container element for the dialog.
Firefox behaves as expected (no flash, no page scroll)

**Comment by fabien-d** [comment] 2013-01-10 00:23
It's weird since the page shouldn't scroll, like you said it's simply a position fix. Sounds like it may not prevent the default event on the button click.
- Does it happen with all three dialogs, or just prompt?
- Can you recreate on the [example site](http://fabien-d.github.com/alertify.js/)?
- Does it append a blank anchor `#` to URL after button click?

If you could provide screenshots and/or post more info (code sample to recreate) I can try to debug.

**Comment by dschwen** [comment] 2013-01-10 00:32
It happens with all three dialogs.
Yeah it happens on the example site as well. 
It does not append a hash. 

I dont know what to show on the screenshot, except for a scrolled-up page ;-).

**Comment by fabien-d** [comment] 2013-01-10 00:36
yeah, fair enough... What OS? And can you reproduce on any other browsers (or are other browsers good like FF)?

**Comment by dschwen** [comment] 2013-01-10 00:40
Ha, sorry, MacOSX 10.7.3. I'll try later at home on Linux and a brand new Chrome. For some reason in my Linux Virtualbox here popping up the dialog freezes up my browsertab.
I also tried Safari and no dialogs show up at all (Version 5.1.5 (7534.55.3))!
As I said FF 17 perfroms perfectly.

**Comment by fabien-d** [comment] 2013-01-10 01:13
I think I was able to reproduce, I'll look into it some more shortly and hopefully get this resolved soon.

**Comment by fabien-d** [comment] 2013-01-10 01:52
Tied to this https://github.com/fabien-d/alertify.js/issues/81 - I can reproduce the Safari 5.1.\* issue where the dialogs don't show which I believe is what you mean by freezes up (dialog doesn't show, but cover does - meaning you can't click on anything)

Still investigating the jump to top issue.

**Comment by fabien-d** [comment] 2013-01-10 12:20
#### Jump to Top

This is a result of setting focus to the OK button or input focus before the animation is complete. Currently a `setTimeout` with a `50ms` delay is used which resolves issues with certain browsers that weren't setting focus at all. Setting a higher delay, e.g. `1000ms` resolved the jump but is really ugly. Looking for a cleaner more reliable approach. (Thinking of using the `transitionend` instead of `setTimeout` to set focus)

#### Dialogs not Showing

There is a parameter of `visibility: hidden` in the `.alertify-hidden` class in the core `alertify.core.css` file. Removing this resolves the dialogs not showing but causes a failure in IE8-. Looking for a solution that will work cross browser.

Thanks for logging the issue - this will help solve major flaws.

**Comment by fabien-d** [comment] 2013-01-10 14:30
Issues should be resolved with ^ pull request.

**Comment by dschwen** [comment] 2013-01-10 15:52
Thanks, just tested it, works well in Chrome and Safari now ! Love your little library. Thanks a bunch again!

**Comment by fabien-d** [comment] 2013-01-10 15:58
Awesome. Closing this issue. If anything comes up simply re-open or log a new one. Cheers

**Closed as completed by fabien-d** 2013-01-10 15:58 UTC

**Comment by fizerkhan** [comment] 2013-09-28 13:14
It is still happens to me. How to fix this bug?

**Comment by sangel10** [comment] 2014-03-03 19:43
I am having the scrolling issue on Chrome 33 on OSX  10.7.5 on version 0.3.11, is there any way to manually fix this?

**Comment by PetrKapishev** [comment] 2014-03-07 09:03
I have this issue in Chrome (Linux) too.
I don't know a nature of this problem, so I had to comment the line 432 (elCallee.focus()) to fix it.

**Comment by sangel10** [comment] 2014-03-07 18:26
PetruhaXI's solution worked for me. I think it might have to do with the fact that I removed the element that called the notification so there was no longer an element to focus on after the call.

**Comment by umair-me** [comment] 2014-04-09 15:42
PetruhaXI's solution worked for me too.

**Comment by toyrunr** [comment] 2015-10-15 21:23
I am having the same problem on Windows 7 in IE11. Page scrolls to top for every alert type displayed. the 432 line is no longer what it used to be. I played around with various "focus" lines of code, to no avail. Thanks
