### ISSUE TITLE
Is it possible to create a prompt dialog with multiple fields?

### ISSUE THREAD

**Issue by Guiming** [fabien-d/alertify.js#238] opened 2014-07-31 10:03 UTC
I see alertify.js prompt dialog can have only one field asking for user input. Is it possible to create a prompt dialog with multiple fields?

**Comment by fabien-d** [comment] 2014-07-31 13:21
duplicate of https://github.com/fabien-d/alertify.js/issues/234

**Closed as completed by fabien-d** 2014-07-31 13:21 UTC
