### ISSUE TITLE
:root *>.alertify-hidden set to display: block insted of display: none

### ISSUE THREAD

**Issue by eilders** [fabien-d/alertify.js#140] opened 2013-05-22 19:07 UTC
Shouldn't

``` css
:root *>.alertify-hidden{display:block}
```

be set to:

``` css
:root *>.alertify-hidden{display:none}
```

This is causing the code to hang around and any link or navigation under it can't be clicked.

I'm using 0.3.9

**Comment by fabien-d** [comment] 2013-05-22 19:28
duplicate of #138.

Setting it to `display: none` prevents the CSS animation from running. A temporary workaround is to add `visibility: hidden;`.

Will be looking for a better solution.

**Comment by eilders** [comment] 2013-05-22 21:42
Appreciate the quick response and workaround.

Apologize for the duplicate.

**Closed as completed** 2013-05-22 21:42 UTC
