### ISSUE TITLE
alertify.confirm doesn't keep focus when tabbing between buttons

### ISSUE THREAD

**Issue by devanddesign** [fabien-d/alertify.js#157] opened 2013-07-10 17:04 UTC
When the alertify.confirm pops up, you should be able to click tab to switch between OK and Cancel.  When you tab once, it switched focus from OK to Cancel but when you click tab again, instead of going back to OK, it switches focus to another element in the underlying page behind the modal.  jQuery UI confirm forces the focus to stay on the buttons in the modal.

**Comment by fabien-d** [comment] 2013-07-10 17:19
Could you provide more information? I'm not able to reproduce this issue as it's something I know has been implemented.
- Which alertify.js version are you using?
- Do you have custom code interacting with it? 
- Browser/OS?

Can you reproduce on the [demo site](http://fabien-d.github.io/alertify.js/)?

**Comment by devanddesign** [comment] 2013-07-11 01:48
Yeah, you're right.  It works fine on the demo site so I must be doing something wrong.  I'll have to do some digging since there's a lot of functionality on my page but I just figured the simple alertify.confirm should work since there's not much to it.

**Comment by fabien-d** [comment] 2013-07-11 02:03
If you're able to isolate the problem - or can replicate the bug with sample code, feel free to pass it along and I'll be glad to help out.

**Comment by fabien-d** [comment] 2013-07-14 20:47
Closing - feel free to reopen if you need more help.

**Closed as completed by fabien-d** 2013-07-14 20:47 UTC
